### ISSUE TITLE
Universidades : Navegabilidade, funções, dados e layout ID:01, ID:02, ID:03, ID:04

### ISSUE THREAD

**Issue by andriuswill** [MORGANAANA/DEV2#16]
Testes passados com os resultados previstos, porém urls informadas nos test cases estão incorretas...

**Comment by MORGANAANA** [comment]
A url foi corrigida, favor executar um smoke test para para que possamos fechar esta demanda.

**Comment by andriuswill** [comment]
Urls corrigidas e retornando o que deve. Testes passaram.
